### ISSUE TITLE
building qts3 gives error

### ISSUE THREAD

**Issue by vidyapiquor** [msorvig/qts3#2]
hi,
I am trying to implement the code in my qt creator and for that i started with test folder while building it is showing error " ASSERT failure in QTest::fetchData(): "Test data requested, but no testdata available."
So can you please guide how to use this code in qt creator . Actually I have to store the image to Amazon s3 bucket and I am stuck. I have tried alot of options but failed. I am using qt 5.7.0 with c++ in windows environment.
Thanks in advance . please help

**Comment by dhruv-mehta99** [comment]
How did you finally upload the image to s3 bucket,i need to upload a csv file can you please help? Thanks in advance
